
/* File generated by gen_cfile.py. Should not be modified. */

#include "LoadPin.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 CO_Physical_Unit_Controller_Output[] =    /* Mapped at index 0x6415, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };
UNS8 CO_Set_point_switch_W_W2[] =   /* Mapped at index 0x6420, subindex 0x01 - 0x01 */
  {
    0x0 /* False */
  };
UNS8 CO_Automatic_Manual_Mode_A_M[] =   /* Mapped at index 0x6421, subindex 0x01 - 0x01 */
  {
    0x0 /* False */
  };
UNS8 CO_Controller_On_Off[] =   /* Mapped at index 0x6422, subindex 0x01 - 0x01 */
  {
    0x0 /* False */
  };
UNS8 CO_Controller_Mode[] =   /* Mapped at index 0x6423, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };
UNS8 CO_Control_Byte[] =    /* Mapped at index 0x6425, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };
UNS16 CO_Status_Word[] =    /* Mapped at index 0x6427, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };
REAL32 Receive_PV[] =   /* Mapped at index 0x6F50, subindex 0x01 - 0x01 */
  {
    0.000000
  };
REAL32 Alternate_Receive_PV[] =   /* Mapped at index 0x6F51, subindex 0x01 - 0x01 */
  {
    0.000000
  };
UNS8 Received_Status[] =    /* Mapped at index 0x6F52, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };
UNS16 AI_Input_FV[] =   /* Mapped at index 0x7100, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };
INTEGER16 AI_Input_PV[] =   /* Mapped at index 0x7130, subindex 0x01 - 0x01 */
  {
    0x0 /* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Load_Pin_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Load_Pin_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Load_Pin_iam_a_slave = 1;

TIMER_HANDLE Load_Pin_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Load_Pin_obj1000 = 0x0;  /* 0 */
                    subindex Load_Pin_Index1000[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Load_Pin_obj1001 = 0x0; /* 0 */
                    subindex Load_Pin_Index1001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Load_Pin_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1003[] =
                    {
                      0x0 /* 0 */
                    };
                    ODCallback_t Load_Pin_Index1003_callbacks[] =
                     {
                       NULL,
                       NULL,
                     };
                    subindex Load_Pin_Index1003[] =
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Load_Pin_obj1005 = 0x80; /* 128 */
                    ODCallback_t Load_Pin_Index1005_callbacks[] =
                     {
                       NULL,
                     };
                    subindex Load_Pin_Index1005[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Load_Pin_obj1006 = 0x0;  /* 0 */
                    ODCallback_t Load_Pin_Index1006_callbacks[] =
                     {
                       NULL,
                     };
                    subindex Load_Pin_Index1006[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1006 }
                     };

/* index 0x100C :   Guard Time */
                    UNS16 Load_Pin_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */
                    UNS8 Load_Pin_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 Load_Pin_obj1014 = 0x81; /* 129 */
                    subindex Load_Pin_Index1014[] =
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Load_Pin_highestSubIndex_obj1016 = 0;
                    UNS32 Load_Pin_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */
                    UNS16 Load_Pin_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Load_Pin_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1018_Vendor_ID = 0x0;  /* 0 */
                    UNS32 Load_Pin_obj1018_Product_Code = 0x0; /* 0 */
                    UNS32 Load_Pin_obj1018_Revision_Number = 0x0;  /* 0 */
                    UNS32 Load_Pin_obj1018_Serial_Number = 0x0;  /* 0 */
                    subindex Load_Pin_Index1018[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1018_Serial_Number }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Load_Pin_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x67F; /* 1831 */
                    UNS32 Load_Pin_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x5FF;  /* 1703 */
                    UNS8 Load_Pin_obj1280_Node_ID_of_the_SDO_Server = 0x7F;  /* 127 */
                    subindex Load_Pin_Index1280[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Load_Pin_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1400_COB_ID_used_by_PDO = 0x1FF; /* 639 */
                    UNS8 Load_Pin_obj1400_Transmission_Type = 0x1; /* 1 */
                    UNS16 Load_Pin_obj1400_Inhibit_Time = 0x0; /* 0 */
                    UNS8 Load_Pin_obj1400_Compatibility_Entry = 0x0; /* 0 */
                    UNS16 Load_Pin_obj1400_Event_Timer = 0x0;  /* 0 */
                    UNS8 Load_Pin_obj1400_SYNC_start_value = 0x0;  /* 0 */
                    subindex Load_Pin_Index1400[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Load_Pin_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Load_Pin_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Load_Pin_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1401_COB_ID_used_by_PDO = 0x2FF; /* 895 */
                    UNS8 Load_Pin_obj1401_Transmission_Type = 0x1; /* 1 */
                    UNS16 Load_Pin_obj1401_Inhibit_Time = 0x0; /* 0 */
                    UNS8 Load_Pin_obj1401_Compatibility_Entry = 0x0; /* 0 */
                    UNS16 Load_Pin_obj1401_Event_Timer = 0x0;  /* 0 */
                    UNS8 Load_Pin_obj1401_SYNC_start_value = 0x0;  /* 0 */
                    subindex Load_Pin_Index1401[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Load_Pin_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Load_Pin_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_obj1401_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Load_Pin_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1600[] =
                    {
                      0x71300110  /* 1898971408 */
                    };
                    subindex Load_Pin_Index1600[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Load_Pin_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 Load_Pin_obj1601[] =
                    {
                      0x71000110  /* 1895825680 */
                    };
                    subindex Load_Pin_Index1601[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Load_Pin_obj1601[0] }
                     };

/* index 0x6415 :   Mapped variable CO Physical Unit Controller Output */
                    UNS8 Load_Pin_highestSubIndex_obj6415 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6415[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6415 },
                       { RW, uint32, sizeof (UNS32), (void*)&CO_Physical_Unit_Controller_Output[0] }
                     };

/* index 0x6420 :   Mapped variable CO Set point switch W-W2 */
                    UNS8 Load_Pin_highestSubIndex_obj6420 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6420[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6420 },
                       { RW, boolean, sizeof (UNS8), (void*)&CO_Set_point_switch_W_W2[0] }
                     };

/* index 0x6421 :   Mapped variable CO Automatic-Manual Mode A-M */
                    UNS8 Load_Pin_highestSubIndex_obj6421 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6421[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6421 },
                       { RW, boolean, sizeof (UNS8), (void*)&CO_Automatic_Manual_Mode_A_M[0] }
                     };

/* index 0x6422 :   Mapped variable CO Controller On-Off */
                    UNS8 Load_Pin_highestSubIndex_obj6422 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6422[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6422 },
                       { RW, boolean, sizeof (UNS8), (void*)&CO_Controller_On_Off[0] }
                     };

/* index 0x6423 :   Mapped variable CO Controller Mode */
                    UNS8 Load_Pin_highestSubIndex_obj6423 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6423[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6423 },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_Controller_Mode[0] }
                     };

/* index 0x6425 :   Mapped variable CO Control Byte */
                    UNS8 Load_Pin_highestSubIndex_obj6425 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6425[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6425 },
                       { RW, uint8, sizeof (UNS8), (void*)&CO_Control_Byte[0] }
                     };

/* index 0x6427 :   Mapped variable CO Status Word */
                    UNS8 Load_Pin_highestSubIndex_obj6427 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6427[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6427 },
                       { RO, uint16, sizeof (UNS16), (void*)&CO_Status_Word[0] }
                     };

/* index 0x6F50 :   Mapped variable Receive PV */
                    UNS8 Load_Pin_highestSubIndex_obj6F50 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6F50[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6F50 },
                       { RW, real32, sizeof (REAL32), (void*)&Receive_PV[0] }
                     };

/* index 0x6F51 :   Mapped variable Alternate Receive PV */
                    UNS8 Load_Pin_highestSubIndex_obj6F51 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6F51[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6F51 },
                       { RW, real32, sizeof (REAL32), (void*)&Alternate_Receive_PV[0] }
                     };

/* index 0x6F52 :   Mapped variable Received Status */
                    UNS8 Load_Pin_highestSubIndex_obj6F52 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index6F52[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj6F52 },
                       { RW, uint8, sizeof (UNS8), (void*)&Received_Status[0] }
                     };

/* index 0x7100 :   Mapped variable AI Input FV */
                    UNS8 Load_Pin_highestSubIndex_obj7100 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index7100[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj7100 },
                       { RO, uint16, sizeof (UNS16), (void*)&AI_Input_FV[0] }
                     };

/* index 0x7130 :   Mapped variable AI Input PV */
                    UNS8 Load_Pin_highestSubIndex_obj7130 = 1; /* number of subindex - 1*/
                    subindex Load_Pin_Index7130[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Load_Pin_highestSubIndex_obj7130 },
                       { RO, int16, sizeof (INTEGER16), (void*)&AI_Input_PV[0] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Load_Pin_objdict[] =
{
  { (subindex*)Load_Pin_Index1000,sizeof(Load_Pin_Index1000)/sizeof(Load_Pin_Index1000[0]), 0x1000},
  { (subindex*)Load_Pin_Index1001,sizeof(Load_Pin_Index1001)/sizeof(Load_Pin_Index1001[0]), 0x1001},
  { (subindex*)Load_Pin_Index1005,sizeof(Load_Pin_Index1005)/sizeof(Load_Pin_Index1005[0]), 0x1005},
  { (subindex*)Load_Pin_Index1006,sizeof(Load_Pin_Index1006)/sizeof(Load_Pin_Index1006[0]), 0x1006},
  { (subindex*)Load_Pin_Index1014,sizeof(Load_Pin_Index1014)/sizeof(Load_Pin_Index1014[0]), 0x1014},
  { (subindex*)Load_Pin_Index1018,sizeof(Load_Pin_Index1018)/sizeof(Load_Pin_Index1018[0]), 0x1018},
  { (subindex*)Load_Pin_Index1280,sizeof(Load_Pin_Index1280)/sizeof(Load_Pin_Index1280[0]), 0x1280},
  { (subindex*)Load_Pin_Index1400,sizeof(Load_Pin_Index1400)/sizeof(Load_Pin_Index1400[0]), 0x1400},
  { (subindex*)Load_Pin_Index1401,sizeof(Load_Pin_Index1401)/sizeof(Load_Pin_Index1401[0]), 0x1401},
  { (subindex*)Load_Pin_Index1600,sizeof(Load_Pin_Index1600)/sizeof(Load_Pin_Index1600[0]), 0x1600},
  { (subindex*)Load_Pin_Index1601,sizeof(Load_Pin_Index1601)/sizeof(Load_Pin_Index1601[0]), 0x1601},
  { (subindex*)Load_Pin_Index6415,sizeof(Load_Pin_Index6415)/sizeof(Load_Pin_Index6415[0]), 0x6415},
  { (subindex*)Load_Pin_Index6420,sizeof(Load_Pin_Index6420)/sizeof(Load_Pin_Index6420[0]), 0x6420},
  { (subindex*)Load_Pin_Index6421,sizeof(Load_Pin_Index6421)/sizeof(Load_Pin_Index6421[0]), 0x6421},
  { (subindex*)Load_Pin_Index6422,sizeof(Load_Pin_Index6422)/sizeof(Load_Pin_Index6422[0]), 0x6422},
  { (subindex*)Load_Pin_Index6423,sizeof(Load_Pin_Index6423)/sizeof(Load_Pin_Index6423[0]), 0x6423},
  { (subindex*)Load_Pin_Index6425,sizeof(Load_Pin_Index6425)/sizeof(Load_Pin_Index6425[0]), 0x6425},
  { (subindex*)Load_Pin_Index6427,sizeof(Load_Pin_Index6427)/sizeof(Load_Pin_Index6427[0]), 0x6427},
  { (subindex*)Load_Pin_Index6F50,sizeof(Load_Pin_Index6F50)/sizeof(Load_Pin_Index6F50[0]), 0x6F50},
  { (subindex*)Load_Pin_Index6F51,sizeof(Load_Pin_Index6F51)/sizeof(Load_Pin_Index6F51[0]), 0x6F51},
  { (subindex*)Load_Pin_Index6F52,sizeof(Load_Pin_Index6F52)/sizeof(Load_Pin_Index6F52[0]), 0x6F52},
  { (subindex*)Load_Pin_Index7100,sizeof(Load_Pin_Index7100)/sizeof(Load_Pin_Index7100[0]), 0x7100},
  { (subindex*)Load_Pin_Index7130,sizeof(Load_Pin_Index7130)/sizeof(Load_Pin_Index7130[0]), 0x7130},
};

const indextable * Load_Pin_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
  int i;
  *callbacks = NULL;
  switch(wIndex){
    case 0x1000: i = 0;break;
    case 0x1001: i = 1;break;
    case 0x1005: i = 2;*callbacks = Load_Pin_Index1005_callbacks; break;
    case 0x1006: i = 3;*callbacks = Load_Pin_Index1006_callbacks; break;
    case 0x1014: i = 4;break;
    case 0x1018: i = 5;break;
    case 0x1280: i = 6;break;
    case 0x1400: i = 7;break;
    case 0x1401: i = 8;break;
    case 0x1600: i = 9;break;
    case 0x1601: i = 10;break;
    case 0x6415: i = 11;break;
    case 0x6420: i = 12;break;
    case 0x6421: i = 13;break;
    case 0x6422: i = 14;break;
    case 0x6423: i = 15;break;
    case 0x6425: i = 16;break;
    case 0x6427: i = 17;break;
    case 0x6F50: i = 18;break;
    case 0x6F51: i = 19;break;
    case 0x6F52: i = 20;break;
    case 0x7100: i = 21;break;
    case 0x7130: i = 22;break;
    default:
      *errorCode = OD_NO_SUCH_OBJECT;
      return NULL;
  }
  *errorCode = OD_SUCCESSFUL;
  return &Load_Pin_objdict[i];
}

/*
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Load_Pin_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index Load_Pin_firstIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  7, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index Load_Pin_lastIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  8, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 Load_Pin_ObjdictSize = sizeof(Load_Pin_objdict)/sizeof(Load_Pin_objdict[0]);

CO_Data Load_Pin_Data = CANOPEN_NODE_DATA_INITIALIZER(Bulon);
