
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef LOADPIN_H
#define LOADPIN_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Bulon_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Bulon_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Load_Pin_Data;
extern UNS32 CO_Physical_Unit_Controller_Output[1];		/* Mapped at index 0x6415, subindex 0x01 - 0x01 */
extern UNS8 CO_Set_point_switch_W_W2[1];		/* Mapped at index 0x6420, subindex 0x01 - 0x01 */
extern UNS8 CO_Automatic_Manual_Mode_A_M[1];		/* Mapped at index 0x6421, subindex 0x01 - 0x01 */
extern UNS8 CO_Controller_On_Off[1];		/* Mapped at index 0x6422, subindex 0x01 - 0x01 */
extern UNS8 CO_Controller_Mode[1];		/* Mapped at index 0x6423, subindex 0x01 - 0x01 */
extern UNS8 CO_Control_Byte[1];		/* Mapped at index 0x6425, subindex 0x01 - 0x01 */
extern UNS16 CO_Status_Word[1];		/* Mapped at index 0x6427, subindex 0x01 - 0x01 */
extern REAL32 Receive_PV[1];		/* Mapped at index 0x6F50, subindex 0x01 - 0x01 */
extern REAL32 Alternate_Receive_PV[1];		/* Mapped at index 0x6F51, subindex 0x01 - 0x01 */
extern UNS8 Received_Status[1];		/* Mapped at index 0x6F52, subindex 0x01 - 0x01 */
extern UNS16 AI_Input_FV[1];		/* Mapped at index 0x7100, subindex 0x01 - 0x01 */
extern INTEGER16 AI_Input_PV[1];		/* Mapped at index 0x7130, subindex 0x01 - 0x01 */

#endif // LOADPIN_H
